version: '3.8'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat_app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - mysql
    networks:
      - appnet
    environment:
      JPDA_ADDRESS: "*:5005"
      JPDA_TRANSPORT: "dt_socket"
    command: ["catalina.sh", "run", "-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n"]

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proyecto_final
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./proyecto_final.sql:/docker-entrypoint-initdb.d/proyecto.sql
    networks:
      - appnet

networks:
  appnet:

volumes:
  mysql_data:
